### ISSUE TITLE
Error: frame header bad format

### ISSUE THREAD

**Issue by Butterfly-Dragon** [gbouthenot/mp3splitter-js#2] opened 2019-12-25 23:19 UTC
I am receiving the following error while trying to split chapters from files downloaded and converted via OpenAudible 1.6.4

```
Id3v2 frame header: Uint8Array [ 255, 251, 80, 0, 0, 0, 0, 0, 0, 0 ]
D:\Downloads\Downloader\!Convert Aax To Mp3\mp3splitter\mp3splitter.js:737
                throw new Error('frame header bad format')
                ^

Error: frame header bad format
    at Mp3splitter.go (D:\Downloads\Downloader\!Convert Aax To Mp3\mp3splitter\mp3splitter.js:737:23)
    at Cliapp.go (D:\Downloads\Downloader\!Convert Aax To Mp3\mp3splitter\mp3splitter.js:36:17)
    at Object.<anonymous> (D:\Downloads\Downloader\!Convert Aax To Mp3\mp3splitter\mp3splitter.js:814:8)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

what can i do to help pinpoint the source of the error? Let me know about how to share the files.

For now i'll paste here the output of a batch file i made along with the batch file.

[MP3Splitter.bat.txt](https://github.com/gbouthenot/mp3splitter-js/files/4000883/MP3Splitter.bat.txt)

[SPLIT LOG.txt](https://github.com/gbouthenot/mp3splitter-js/files/4000881/SPLIT.LOG.txt)

**Comment by gbouthenot** [comment] 2019-12-26 07:12
I think the issue is related to the fact that your script does not do wildcard expansion. It feeds "*.mp3" to xcopy that do nothing (see : 0 file copied), then it call mp3splitter with this "*.mp3" non existent file name. You can see there is a file not found error in your log file.

But mp3splitter should throw an error in this case, I can't see why it doesn't. I will see why in a few days when I go back to home.

I suggest to debug your script and see why your FOR loop does not expand *.mp3 filenames.
Linux bash does this, I am sure that cmd.exe does not, but there may be some magic that may process the expansion, i am not a Windows script expert.

**Comment by Butterfly-Dragon** [comment] 2019-12-26 10:35
?! 😅

You can see that it does expand the filenames because in the log it writes
down the file names.

It's because your script fails that it finds no files to feed to xcopy.

Also, it worked up until this 16th december, at christmas i went into a
shopping spree and bought 67 audiobooks, plus one that was already in
preorder and released, went to convert them via openaudible, but it told me
to update to 1.6.4.

Now i cannot split the chapters.

In the previous error of the same kind you said there should be 7 bits
allocated and pointed at the numbers shown, now, if i am reading the error
correctly they are allocating 8 bits, since the numbers you were referring
to before you complained they should not go above 128 here they stop at
255, also they look sequenced in the opposite way.

I can still see the chapters if i open the MP3s so it is probably something
different.

Openaudible now can split into chapters but it requires me to go file by
file, hence me making your script part of a batch file.

**Comment by gbouthenot** [comment] 2020-01-05 14:51
I'm back to home. Sorry for the delay. I am not a cmd.exe batch expert !
You're right, your script does not filename expansion and feeds the file to the .js script.
The "file not found" is actually related to "xcopy" and "recycle.exe", which appears after the splitter call.

The frame header: Uint8Array seems to be a MP3 frame instead of a ID3v2 frame. This is not what the program is waiting for, the mp3 seems not to be structured the way it should, or contain a extension that mp3splitter is not aware of. It is probably a bug from mp3splitter.

Can you please provide a sample of a file that produce this error, for investigation ?
I would like you to send me the start of the file ? (the first 600 Ko) please put it somewhere and send me the link by mail (get my email at https://github.com/gbouthenot)

Thank you !

**Comment by Butterfly-Dragon** [comment] 2020-01-05 20:23
Okay i did a *very raw* file cut as to avoid touching the file as much as possible, and included the checksum, just to be safe. It's all in the zip attached to this message.

Thanks for all your work.

[master.zip](https://github.com/gbouthenot/mp3splitter-js/files/4023976/master.zip)

**Comment by gbouthenot** [comment] 2020-01-06 12:06
Thank you. I got the file. It seems the program used to produce this file use a bugged ID3v2 library, because, the total frame size is set to 566036 bytes instead of 566012.
So at the end of the ID3 frames, the decoder is still reading 24 bytes to be ID3 frame. 10 bytes are padding, and then, the real MP3 frames begin.
Tested with foobar2000, which does frame resynchronisation the first mp3 frame is lost. This has no incidence because it is a Xing MP3 frame (used for fast forwarding in the file), and this frame is recreated by mp3splitter for each file. When you play the files you don't see a problem because resync is part of every player.

The 24 bytes MIGHT be the APIC (picture) header (the one with mimetype and image description), that have been counted twice. I don't have other samples of bugged files.

I don't know the right way to deal with it. The choices are:
- Ignore bad ID3 header frames (and mungle the first mp3 frame)
- Consider a mp3 frame header inside the ID3v2 tag to end the ID3 tag.

Can you provide other files that have this issue ?

I'm still digging into your file if I find something other.

**Comment by Butterfly-Dragon** [comment] 2020-01-06 12:14
Now that you told me what to look for i double-checked.

Yes, it's the same on all files downloaded with Openaudible 1.6.4. regardless of when they were produced.

Will open an issue with them, and try to get an answer on why.

Converting the stuff i bought is nice but not when i have to keep them as humongous files, and i have to go file by file to convert them.

Well... at least this solves part of the problem. Now i'll get an answer from them to see if it's a "new feature" or an actual bug

**Comment by gbouthenot** [comment] 2020-01-06 15:27
Seems related to new version. It is probably a bug either in openAudible or in ffmpeg.
With previous versions, the id3 tag has the right size (10 padding bytes), now it seems it the tag is 14 more, but it mungle the first mp3 frame.
I'm still looking ...

edit: it is definitely related to ffmpeg "ffmpeg version N-96259-g944203270d-ffmpeg-windows-build-helpers"

**Comment by Butterfly-Dragon** [comment] 2020-01-06 15:40
Hmm... i thought so too. But in the file i sent you i had swapped the nightly build with the 4.2.1 version in \OpenAudible\bin\win so, unless it's picking up FFMPEG somewhere else i have no idea. The only other FFMPEGs i have on my PC are the one Python uses in python's folder (which, admittedly is in the PATH, but then again that too is 4.2.1) and the nightly build i have on a different folder outside of path and elsewhere which i call only when needed.

**Comment by gbouthenot** [comment] 2020-01-06 15:42
I added a commit to "Ignore bad ID3 header frames (and mungle the first mp3 frame)" :
This should fix your problems by mangling the first frame (xing so no damage)
https://github.com/gbouthenot/mp3splitter-js/tree/b65d21a3e399779994d26ee0bfc12df94fdfcf3d

But ffmpeg should not produce bogus file. I will investigate.

**Comment by Butterfly-Dragon** [comment] 2020-01-06 15:44
Thank you for all your work

**Comment by gbouthenot** [comment] 2020-01-06 16:01
Just tested:
- openAudible 1.5.4 : ffmpeg-N76456 -> OK
- openAudible 1.6.4 : ffmpeg-N96259 -> Bad size
So the problem is clearly coming from ffmpeg

**Comment by ValZapod** [comment] 2020-01-09 15:46
https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAAJ4pEy-y8bpc3LBYDEk0gr=Ononw2Nj+rdf=OLWcsk3tu1cVg@mail.gmail.com/

**Comment by gbouthenot** [comment] 2020-01-10 14:31
This issue was caused in bug in recent ffmpeg. I proposed a patch that have been committed to the main source tree.
I modified mp3splitter-js so ti no-longer throws an error when it encounters this issue.

**Closed as completed by gbouthenot** 2020-01-10 14:31 UTC
